apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mfasi7863/k8s_application.git
    targetRevision: HEAD
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true        # delete resources removed from git
      selfHeal: true     # revert manual changes to match git
    syncOptions:
      - CreateNamespace=true
