name: Build and Push Frontend Image to ECR

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get AWS creds from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: jwt
          role: github-terraform
          jwtGithubAudience: "https://github.com/mfasi7863"
          secrets: |
            aws/creds/terraform-role access_key     | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key     | AWS_SECRET_ACCESS_KEY ;
            aws/creds/terraform-role security_token | AWS_SESSION_TOKEN

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            672296383659.dkr.ecr.ap-south-1.amazonaws.com/terraform-aws-ecr:latest
            672296383659.dkr.ecr.ap-south-1.amazonaws.com/terraform-aws-ecr:${{ github.sha }}